spring:
  application:
    name: url-shortener
  groovy:
    template:
      check-template-location: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false

url:
  short:
    root: http://localhost:8080